# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Intempt Demo Shop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Intempt Demo Shop
 pod 'Stripe'
  pod 'Alamofire'
pod 'Kingfisher'
  pod 'Auth0'

pod 'FBSDKCoreKit'  
pod 'FBSDKLoginKit'
  pod 'FacebookLogin'

end
